### ISSUE TITLE
can't add checkbox input

### ISSUE THREAD

**Issue by justin-hackin** [Lesha-spr/react-validation#10]
Common use case for validation: checkbox to agree to Terms of Service.  Currently no way to pass checked value to a rule.  Consider at least accepting pending https://github.com/Lesha-spr/react-validation/pull/8 so that we can at  access the dom element to check the checked property

**Comment by Lesha-spr** [comment]
Hi Justin,

You can use Validation to validate checkbox - just make `type` attribute to `checkbox`. Don't forget to pass value to it. Validation will check the `value` of the component, and if it's not `checked` will mark it as not-valid.

I've updated [demo](http://lesha-spr.github.io/react-validation/) to demonstrate it.
