### ISSUE TITLE
Cannot read property 'rule' of undefined

### ISSUE THREAD

**Issue by MaxwellGover** [Lesha-spr/react-validation#106]
![screen shot 2017-06-16 at 2 47 06 pm](https://user-images.githubusercontent.com/11525891/27240456-c029ea0c-52a2-11e7-9791-0e608fbb65d4.png)

**Comment by sidati** [comment]
This is probably you add an un-existed rule or mis-write it, so check your form Inputs/selects validation attribute 😎
