### ISSUE TITLE
errors not initialized nor are displayed on attempted submit

### ISSUE THREAD

**Issue by justin-hackin** [Lesha-spr/react-validation#11]
I think I should be prompted with the error messages on initialization or upon trying try click a disabled submit button so I know what is missing in order to enable submit.

**Comment by Lesha-spr** [comment]
Hi Justin,

Would it be OK to have some interface, kinda `forceValidate` on `Form` component?

Thank you in advance.

**Comment by Lesha-spr** [comment]
Hi Justin,

I've added `forceValidate` to Form component. Please check [demo](http://lesha-spr.github.io/react-validation/) (Subsciption form) to find usage.

Thanks,
Oleksii
