### ISSUE TITLE
Version of NPM package is still 2.10.9

### ISSUE THREAD

**Issue by shenphen** [Lesha-spr/react-validation#119]
Like in topic - latest version of NPM package is still 2.10.9 while in repo is 2.10.10 & cannot upgrade via npm.

**Comment by nokiko** [comment]
Same issue here, I have a project that works with  2.10.10 and not 2.10.9 but cannot use npm in the build process now

**Comment by shenphen** [comment]
OK, now it's version 3 anyways, so I'm closing issue.
