### ISSUE TITLE
lib/build/validation.rc.js  ?

### ISSUE THREAD

**Issue by nokiko** [Lesha-spr/react-validation#121]
Hi

I inherited a project that uses

`import { rules, Form, Input } from 'nm/react-validation/lib/build/validation.rc.js'`   this was there up till version 2.10.10

I see Form input etc all have there own js file now but where should I import the rules from now

**Comment by Lesha-spr** [comment]
Hi @nokiko ,

Now you should define rules as functions and import in any way you like.

Define rule (let's say in ```rules.js```):

```javascript
export const required = (value) => {
  if (!value.toString().trim()) {
    return <span>Required</span>
  }
}
```

Now import it within component you want to validate:

```javascript
// Get needed rules
import { required } from 'rules.js';
// Get validation components
import Form from 'react-validation/build/form.js';
import Input from 'react-validation/build/input.js';

// Define component with validations
export default function() {
  return (
    <Form>
      <Input name="name" validations={[required]} />
    </Form>
  );
}
```

**Comment by shenphen** [comment]
Hello,
@Lesha-spr I've noticed some incongruities in README.md.

In [exaples](https://github.com/Lesha-spr/react-validation#example-usage) importing comes from 'react-validation/components/*', not from 'react-validation/build/*'.

There is also impossible to import [HOCs](https://github.com/Lesha-spr/react-validation#hocs) because they exist only in src folder.

**Comment by Lesha-spr** [comment]
Hi @shenphen ,

HOCs are exported via ```main``` script so:

```javascript
import { form, control, button } from 'react-validation'; // HOCs
import Input from 'react-validation/build/input'; // Input component
```
Updated README

**Comment by nokiko** [comment]
Nice, is is also possible to define the rule in the current class so i can have my localization data. What calls should i use  then

the old call was 

`       class ProductListerItem extends React.Component {
    
    constructor(props, context) {
        super(props, context);
        
        /**
         * Validation rules for quantity form
         */
      Object.assign(rules, {
           numeric: {
              rule: value => {
                 return validator.isNumeric(value.toString());
            },
             hint: value => {
                  return (<span className="alert-negative">{props.localization['productlister.item.quantity.error']}</span>);
              }
           } 
        });
     
        this.state = {
           addToBasketQuantity: 1
        }
    }
    


    createAddToBasketFormElement() {
        return (<Form className="form" onSubmit={this.onAddProductToBasket.bind(this)}>
                    <div className="form-fields">
                        <div className="form-field">
                            <div className="input-combined">
                                <Input className="form-input" type="text" name='quantity' value={this.state.addToBasketQuantity} onChange={(e) => this.onChangeAddToBasketQuantity(e)} validations={[numeric]}  />
                                <Button className="btn btn-submit"><i className="fa fa-shopping-basket"></i></Button>
                            </div>
                        </div>
                    </div>
                </Form>);
    }

`

**Comment by Lesha-spr** [comment]
Now you don't need separated ```rule``` and ```hint``` properties.

So, you can easily define higher-level function which returns function (rule).

```javascript
// Expect currying with error argument
const numeric = function(error) {
  // Abuse closure :)
  return function(value) {
    if (!validator.isNumeric(value.toString())) {
      return <span className="alert-negative">{error}</span>
    }
  }
};

class Example extends Component {
  constructor(props) {
    super(props);

    // Call with pre-defined error based on props
    const numericWithError = numeric(props.localization['productlister.item.quantity.error']);

    // Save to instance property
    this.validations = [numericWithError];

    // NOTE: Please be aware 'validations' property should not be literal because each render call will create fresh one
    this.state = {
      addToBasketQuantity: 1
    }
  }
  render() {

    return (
      <div>
        <Input className="form-input" type="text" name='quantity' value={this.state.addToBasketQuantity} onChange={(e) => this.onChangeAddToBasketQuantity(e)} validations={this.validations}  />
      </div>
    )
  }
}
```

**Comment by nokiko** [comment]
This works perfect, interesting solution

thank you
