### ISSUE TITLE
packaging of v3

### ISSUE THREAD

**Issue by Mairu** [Lesha-spr/react-validation#124]
At the current version 3.0.3 in an empty project, `npm install react-validation` will load 186MB, because of all the dependencies.

> + react-validation@3.0.3
> added 1273 packages in 143.145s

It would be really nice if you can move the dependencies to devDependencies again, and also remove the postinstall script (it fails on older node version f.e. the meteor bundled version). The build script should run before creating the npm package, so i would suggest to use "prepare" instead of "postinstall".

Additionally you could add a files section or an .npmignore ( https://docs.npmjs.com/files/package.json#files ) because the config, or App files are not needed in the npm package.

I would also add a pull request, if wanted.

**Comment by Lesha-spr** [comment]
Hi @Mairu ,

Oh dear, it's too much. I'll update asap.

Thanks

**Comment by Lesha-spr** [comment]
Just pushed and published. Should be fine.

**Comment by Mairu** [comment]
Thanks.

What perhaps could also be done would be to use react as peer dependency.
As example see https://github.com/JedWatson/react-select/blob/master/package.json

**Comment by Lesha-spr** [comment]
@Mairu , peerDependencies are deprecated. Do you think it's good idea?

**Comment by Mairu** [comment]
The behaviour has changed since npm 3 but it is not deprecated.
https://docs.npmjs.com/files/package.json#peerdependencies

So the package is not installed (for react-validation) and the main projects version is used. I think that is a good approach. At least if you dont want to use new features of react v16.
