### ISSUE TITLE
Module build failed: Error: Using `babel-preset-react-app` requires that you specify `NODE_ENV` or `BABEL_ENV`

### ISSUE THREAD

**Issue by nokiko** [Lesha-spr/react-validation#125]
Hi

Never got this error in the older 2.x versions but in the 3 versions I get this error with webpack

ERROR in ./node_modules/react-validation/build/input.js
    Module build failed: Error: Using `babel-preset-react-app` requires that you specify `NODE_ENV` or `BABEL_ENV` environment variables.

**Comment by Lesha-spr** [comment]
Hi @nokiko ,

Should be fine with 3.0.4. Please update
