### ISSUE TITLE
 ERROR in ./node_modules/react-validation/build/button.js     Module build failed: Error: Couldn't find preset "react-app" relative

### ISSUE THREAD

**Issue by nokiko** [Lesha-spr/react-validation#126]
After updating t the new version  no longer get the error for the node env but I do get this one  

 ERROR in ./node_modules/react-validation/build/button.js
    Module build failed: Error: Couldn't find preset "react-app" relative to directory "..componentset\\_sources\\default\\_webpack\\node_modules\\react-validation"
        at \_webpack\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19

**Comment by Lesha-spr** [comment]
Hm, is it occurs on installation or after import to your app?
I actually can't reproduce it within "clean" project without "react-app" preset installed.

**Comment by nokiko** [comment]
this happended to me after i updated the package and then dit an npm install and when i called webpack i saw this error

**Comment by Lesha-spr** [comment]
Please, try to update now. I'm not sure what's the source of the issue - removed babel configuration from package.json.

Actually, package should not run any scripts after update - it's now pre-builded before publish.

**Comment by nokiko** [comment]
All seems to be working now
