### ISSUE TITLE
how to bind value on state

### ISSUE THREAD

**Issue by sinkcup** [Lesha-spr/react-validation#16]
```
<Validation.Input value="foo" ref='username' name='username' validations={[{rule: 'isRequired'}]} />
```

above is OK. but this is useless:

```
this.state.name = 'foo';
<Validation.Input value={this.state.name} ref='username' name='username' validations={[{rule: 'isRequired'}]} />
this.setState({ name: 'bar' });
```

in react official docs, we should use value to bind. see https://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by Lesha-spr** [comment]
Hi @sinkcup ,

This could be very major. Do you have a workaround? I'll try to prepare fix till the end of the week.

Thanks,
Oleksii

**Comment by Lesha-spr** [comment]
Hi @sinkcup ,

Please checkout [fix](https://github.com/Lesha-spr/react-validation/commit/70149985388e131d98a7253536058c1c3082088c) (@1.6.4) for this issue. Hope this help.

Please close issue if everything is fine.

Thanks,
Oleksii

**Comment by kidequinox** [comment]
still having trouble with this. using latest version.
can't get ref's value. 

`handleChange: function(){
		this.setState({
				username: this.refs.username.value,
		});
},
<Validation.Input ref='username' value={this.state.username} name='username' onChange={this.handleChange} validations={[{rule: 'isRequired'},]} />
`

**Comment by kidequinox** [comment]
still having issues with this. can not get "this.refs.username.value" in the submit function or link a state value properly.
