### ISSUE TITLE
Input type=checkbox onChange is not called.

### ISSUE THREAD

**Issue by wiadev** [Lesha-spr/react-validation#164]
Hi
Input type=checkbox onChange is not called.
Here is the code snippets.
```
<Input type="checkbox" value="1" name="policy" checked={this.state.isChecked} onChange={this.handleCheckboxChange} />
```
If I change type to text, handleCheckboxChange is called nicely.
Any idea?

**Comment by cblaettl** [comment]
You have to use the `onClick` handler of the checkbox. The `onChange` handler of a checkbox doesn't fire. 
But this isn't related to this package at all, it's just a general react / js thing.
