### ISSUE TITLE
forceValidate on disabled button?

### ISSUE THREAD

**Issue by snakeyak** [Lesha-spr/react-validation#17]
Is there a way to run forceValidate upon clicking a currently disabled <Validate.Input> submit button? It appears the onClick is being blocked by the component if button is in disabled state

Thanks

**Comment by Lesha-spr** [comment]
Hi @snakeyak ,

Not sure this is a good idea. Component actually doesn't block onClick event on disabled button - browsers does and this is by design.

As a workaround (not the best for sure) you could try to use native `<button/>` component with some conditional appearance.

Thanks,
Oleksii

**Comment by snakeyak** [comment]
Thank you, makes sense
