### ISSUE TITLE
latest validator?

### ISSUE THREAD

**Issue by snakeyak** [Lesha-spr/react-validation#18]
Hi,

Any plans on updating this to work with latest validator (5.2.0 +) ? It doesn't seem to work with it currently, which is a shame, a lot of fixes released since the required 3.41.2 

Thank you

**Comment by Lesha-spr** [comment]
Hi @snakeyak ,

Please check out 1.6.7 version. Validator@5.2.0 is now supported.
If everything is OK please close the issue.

Regards,
Oleksii

**Comment by snakeyak** [comment]
Amazeballs, thank you for fixing it so quickly!
