### ISSUE TITLE
Radio Buttons ?

### ISSUE THREAD

**Issue by kidequinox** [Lesha-spr/react-validation#19]
How would I implement radio buttons ?

**Comment by snakeyak** [comment]
This is what I'm using to validate radio buttons (the only thing to validate is whether any has been selected). Hope this helps


`      <input type="radio" data-code="a" onClick={this.onRadioClick.bind(this)} />
      <input type="radio" data-code="b" onClick={this.onRadioClick.bind(this)} />

      (...)

    onRadioClick(e) {
      this.setState({
        radioSelected: e.target.getAttribute('data-code');
      }) 
  }

      validate() {
       if (!this.state.radioSelected) {
        valid = false;
        this.setState({showRequiredNotice: true})
      }
  }`

**Comment by kidequinox** [comment]
Works good! i get it now. thanks for the help!!
