### ISSUE TITLE
Doesn't work with ES6 react components

### ISSUE THREAD

**Issue by raelmiu** [Lesha-spr/react-validation#2]
I get failure to use setState() and forceUpdate() functions.

**Comment by raelmiu** [comment]
From what I understand. This should just no longer be done on DOM elements at all.

**Comment by Lesha-spr** [comment]
Hi Jesper,

I'll look to it a bit later. Could you please give me broken code?

Thanks,
Oleksii

2015-11-23 16:09 GMT+02:00 Jesper Bylund <notifications@github.com>:

**Comment by raelmiu** [comment]
I've tested a bit more since then and the problem is this:
When a button is NOT a Validator.Button setState breaks, setAttribute(disabled, true) works though.
But when all buttons are Validator.Button everything works perfectly. 
Sorry about the misleading first comments!

**Comment by Lesha-spr** [comment]
I've updated condition of 'type' check. Please update to @1.4.6
