### ISSUE TITLE
Binding to state

### ISSUE THREAD

**Issue by kidequinox** [Lesha-spr/react-validation#20]
Using version 1.6.7. still having issues with this. When I use react-validation can not get "this.refs.username.value" in the submit function or bind to state.

**Comment by Lesha-spr** [comment]
Hi @kidequinox ,

This is true. The reason is React 15.0 release - ref is now private property so I can't access it on clone stage.
As a workaround you still can access the value of the DOM element (input) via ref to the Validation component:
this.refs.username.state.value
