### ISSUE TITLE
Custom onClick

### ISSUE THREAD

**Issue by murphysierra** [Lesha-spr/react-validation#21]
Hello!  I would love a way to use your Validation library with a button that is not the submit button.  I currently have an email form with a`+`  `Validation.Button` to add a valid email to my React component state, and a `Share` button to send emails to the addresses stored in state when not empty.  I would love to be able to disable my `Share` button with the same constraints as my `+` button plus a customized rule.

The problem is that I need the `Share` button to not be a "submit" button, and have it instead trigger a `sendShareEmail()` function.  I'm currently working around it using a generic button and manually disabling it based on certain conditions, but I would rather stay consistent and use your library to disable both buttons and reduce repetition.  An `onClick` prop for the `Validation.Button` would be a great addition.  Thanks so much!

**Comment by Lesha-spr** [comment]
Hi @murphysierra ,

I'm now working to extend the Validation component and handle any button types. For now please checkout 1.7.1 version.

As a workaround you can still use Validation.Button with 'submit' type and preventDefault() on it's click handler to avoid form submition. This is not a pretty solution but still will fix your problem.
Is that OK?

Please feel free to continue talking on this issue.

Thanks,
Oleksii
