### ISSUE TITLE
Email Validation

### ISSUE THREAD

**Issue by Themandunord** [Lesha-spr/react-validation#27]
Hello,

I need to check if email is already in use for a subcription.
I use Meteor with MongoDB.

I create a rule : 
`isEmailExist: {
                className: 'erreur',
                message: "Already in use",
                rule: function (value) {
                    Meteor.call('account_creation.checkEmailExist', value, function (error, result) {
                        if (error) {
                            console.log(error)
                        }
                        console.log(result)
                        return !result;
                    })
                }
            }`

The call to MongoDB works; result return true ou false if email exist.
But the validation is always false.. the error message is always show.

How can I do that ? 

Thanks.

**Comment by Lesha-spr** [comment]
Hi @Themandunord ,

'rule' function returns nothing (undefined) - this is the reason you are facing always false. I think Meteor.call returns Promise. Is it correct? Validation doesn't work with Promises at the moment.

I'll take a look to support of async validation in the nearest future.

As a workaround you could use showError method of Input component and call it asynchronously on API response.

**Comment by Themandunord** [comment]
Thanks @Lesha-spr,

Yes meteor use Promise.

I'll try the showError method :+1: 
I'll tell you when I have done this !

**Comment by Themandunord** [comment]
Hi @Lesha-spr,

I have a big problem of comprehension.. can you help me ? 

Here my component : https://gist.github.com/Themandunord/c6cac7612f6cc20be686502612cf6487

I have many erros :

1. I have problems to get some ref... For example, I need to get refs in componentDidMount because on either function, this.refs is empty.

2. I make a function onBlur to validate if email already exist in DB. It's work fine with showError() ! But when I want the submit to be deactivate if this input show error. Now, the button is activate whereas the email input show error.

3. Why my ref for the submitBtn was replace by the submit13 ?

**Comment by Lesha-spr** [comment]
Hi @Themandunord ,

Sorry for been missing for a while. Here is what I came with:
1. Refs are now fixed (please checkout @1.7.3) with one 'but' - when your'e referencing to a controlled input(select/button) you will receive Component object (not a DOM node). I've added public method getElement to the controlled Components so you can catch them.

2. I'm not sure if this is common. Could you please provide a way you want it to come? It should block a submit buttons every time you call showError, am I correct?

3. Fixed (please checkout @1.7.3).

**Comment by Themandunord** [comment]
Hi @Lesha-spr 

Thanks for your commit :)

For the point 2. Yes if there are some ShowError in the form, I don't want user to validate the form.
So actually I haven't yet succeeded to deactivate the submit button :/

And I have a second problem only on Chrome.
When the login form is filled by Chrome, the submit button is still deactivate. But I i make a click anywhere on the page, the submit button is activated.

Thanks.

**Comment by Themandunord** [comment]
I @Lesha-spr !

Have you got somes news ?
