### ISSUE TITLE
File Support

### ISSUE THREAD

**Issue by Cyval** [Lesha-spr/react-validation#29]
Hello again. 
Is there any extension for files in react-validation?
`Validation.Input type=file `works well, but when I use it with form-serialize, it does not "capture" the value of the file itself, so I thought there may be an extension for this one. 

Thanks in advance.

**Comment by Lesha-spr** [comment]
Hi @Cyval ,

Thank you for a question. Unfortunately it's not about a Components - the reason is the form serialization itself. You just can't serialize a file input value (I believe about a security reasons) - use formData API for this case.

**Comment by Cyval** [comment]
Okay thanks. I managed to create a work around since the onChange returns an event, then assign that event to state. Thanks!
