### ISSUE TITLE
FormData returns nothing

### ISSUE THREAD

**Issue by raelmiu** [Lesha-spr/react-validation#3]
In fact I'm not succeeding in getting data from the form in any way on the submit handler.

event.target formdata = null
ref.form.getDOMNode() formdata = null
ref.input.getDomNode() also no available values.

Anyone have any example of a working way to get at form data?

**Comment by Lesha-spr** [comment]
This is not the way it works. <a href="https://developer.mozilla.org/en-US/docs/Web/API/FormData/FormData">Here</a> is the full API documentation about FormData.
