### ISSUE TITLE
Input Wrapper text-area onChange not firing correctly

### ISSUE THREAD

**Issue by sudarshanrao7** [Lesha-spr/react-validation#31]
Hey,

Thanks for the awesome plugin 👍 

I needed a text-area with required validation,some thing like this

`<Validation.Input ref='description'  wrapper="{{ component: 'textarea' }}" className='ui-input form-control'  value="{this.props.description}" ref='description' name='description' validations="{[{rule: 'isRequired'}]}" />`

But the UI would not reflect the changes based on user input.

I noticed that in Input.jsx file - value attribute is missing under this.props.wrapper condition

` if (this.props.wrapper) {
            try {
                props = Object.assign({}, this.props.wrapper.props, this.props);

                input = <this.props.wrapper.component ref='element' {...props} className={this.state.className} checked={this.state.checked} onChange={this._handleChange} onBlur={this._handleBlur}/>;
            } catch(e) {
                console.log(e);
            }
        } else {
            input = <input ref='element' {...this.props} className={this.state.className} checked={this.state.checked} value={this.state.value} onChange={this._handleChange} onBlur={this._handleBlur}/>;
        }`

Adding "value={this.state.value}" for wrapper element seems to fix my issue, wanted to check is there a easier way to do the same without modifying your code base.

PS: Using 1.7.4 version

Thanks
Sudarshan

**Comment by sudarshanrao7** [comment]
Current work around - Wrote new React component extending the Validation.Input class and over-riding just the render method.

**Comment by Lesha-spr** [comment]
Hi @sudarshanrao7 ,

I've recently added Textarea component to split it out. I'm now working on major release and will add more generic way to control validation flow.

Please checkout 1.7.5 for your issue.

Thanks,
Oleksii

**Comment by sudarshanrao7** [comment]
Thanks 👍  Works like a charm
