### ISSUE TITLE
Unknown props on <input>

### ISSUE THREAD

**Issue by PaulieScanlon** [Lesha-spr/react-validation#32]
Hi, i'm pretty new to React and am trying to use react-validation on a simple input form. 
I'm using React 15.2.1 but am getting this error:

Unknown props `validations`, `_registerControl`, `_unregisterControl`, `_validate` on <input>

Here's my input box:

var InputBox = React.createClass({

    onSubmit: function(event) {
        event.preventDefault();
        this.refs.username.showError('Error');
    },

    render: function() {

      return (
          <Validation.Form onSubmit={this.onSubmit}>
              <Validation.Input
              placeholder="User name"
              ref='username'
              name='username'
              validations={[
                {
                  rule: 'isRequired'
                }
              ]} />
              <Validation.Button type='submit' />
          </Validation.Form>
      );
    }
});

Any help would be appreciated!

**Comment by Lesha-spr** [comment]
Hi @PaulieScanlon ,

Please checkout @1.7.5. I've excluded custom props from the attributes of DOM elements. Currentrly I'm working on major 2.0.0 version to apply new features and be in pulse of fresh React version.

Thanks,
Oleksii

**Comment by PaulieScanlon** [comment]
Hey @Lesha-spr Great! I've Just updated to 1.7.5. Looks good to me... a nice clean console, no big red errors :)

**Comment by abnerlinan** [comment]
why i still have warning on version 1.7.5
