### ISSUE TITLE
Unknow prop in console

### ISSUE THREAD

**Issue by Themandunord** [Lesha-spr/react-validation#35]
Hi @Lesha-spr 

I have a warning in the console : 
`Unknow prop for containerClassName, defaultLabelStyle, defaultInputStyle`
And
`Unknown DOM property inputmode`

I've you got a solution ? I'm on 1.7.5.

![react validation](https://cloud.githubusercontent.com/assets/2819925/17263220/3c4de07c-55e0-11e6-9cce-b9b03cc5ac62.PNG)

Thanks

**Comment by snakeyak** [comment]
Same here. This is caused by changes introduced in react 15.2

**Comment by Lesha-spr** [comment]
Hi @Themandunord ,

I've finally released 2.0. Please check it out. There is a tons of bug fixes and this should not be an issue anymore.

Thanks,
Oleksii

**Comment by Lesha-spr** [comment]
https://github.com/Lesha-spr/react-validation/issues/32
