### ISSUE TITLE
Disable / Enable button

### ISSUE THREAD

**Issue by PaulieScanlon** [Lesha-spr/react-validation#36]
Hi, i'm using this for URL validation on a input and it's all working fine..

One thing though. My app does an api lookup using the URL from an input box, so after the URL input is validated the submit button is enabled .. but...

I need to, after onSubmit, disable the button so a user can't do the api look up twice/while the look up is happening.

I will also then need to re-enable the button after the ajax response is returned.

Any ideas how i can do this?

**Comment by snakeyak** [comment]
You can pass `disabled` prop to the button, for example:
```
<Validation.Button
                  type="submit"
                  **disabled={buttonDisabled}**
                  className="btn btn-lg btn-primary button-pay"
                  invalidClassName='invalid'
                  disabledClassName='disabled'
                  value="GO"
                  onClick={this.onSubmitClick.bind(this)}
                />
```

So just keep it in the state whether the button has already been pressed or not and disable it accordingly

**Comment by Lesha-spr** [comment]
Hi @PaulieScanlon ,

As @snakeyak mention you can specify disabled prop and it will suppress the react-validation behavior. Please also checkout 2.0 version - there is tons of fixes and reworks.

Thanks,
Oleksii
