### ISSUE TITLE
import Validation from 'react-validation' does not work

### ISSUE THREAD

**Issue by snakeyak** [Lesha-spr/react-validation#37]
The new version 2.0.1. does not export Validation class, and as such cannot be used by 
```
import Validation from 'react-validation'
```
as per documentation, but would rather have to be 
```
import { Button } from 'react-validation'
```
etc.

Is this intended behaviour (and docs need updating) or an error?

The 1.7.5 version worked like this since it had
`module.exports = Validation;`

**Comment by Lesha-spr** [comment]
Hi @snakeyak ,

I've updated README along with 2.0.1 release. At the moment there is new syntax (TBD):

```javascript
import Validation from 'react-validation';

// Validation.components.Button is like old Validation.Button

// or

import { components } from 'react-validation';

// components.Button
```

**Comment by Lesha-spr** [comment]
[Migration guide](https://github.com/Lesha-spr/react-validation#migration-from-1) might be useful.

**Comment by snakeyak** [comment]
Thank you, that is useful indeed :)
