### ISSUE TITLE
Meteor doesn't run when Object.assign is used

### ISSUE THREAD

**Issue by Cyval** [Lesha-spr/react-validation#38]
Hi, thanks for your great library and updates. I have one concern tho, I am using Meteor and I'm trying to apply the `Object.assign` for extending validations. However, my meteor blows up and logs a very long stack trace. I tried removing the `Object.assign` and reverting back to `.extendErrors` and that did well.

**Comment by Cyval** [comment]
It's version 2.0.1. 
Update: 
I tried using `lodash` and it's working well, however when I do something  to trigger the validation,  it only says, 'validation error'.

**Comment by Lesha-spr** [comment]
Could you please provide a broken code?

**Comment by Cyval** [comment]
I only copied what's in your documentation. I only added

`let _ = lodash`
`_.assign(Validation.rules, {...docs code})`
