### ISSUE TITLE
forceValidate ?

### ISSUE THREAD

**Issue by snakeyak** [Lesha-spr/react-validation#39]
Is there any way to work around the missing forceValidate in v2 ?

I used it in v1 to as I had submit buttons that were not a part of the validation form

**Comment by Lesha-spr** [comment]
Hi @snakeyak ,

I've added ```validateAll``` method within 5b62315bc47cda75f917d5213eddf66384c3575e (2.0.2). Please check it out.

Thanks,
Oleksii

**Comment by snakeyak** [comment]
Thank you
