### ISSUE TITLE
Support for other fields

### ISSUE THREAD

**Issue by JamesDullaghan** [Lesha-spr/react-validation#4]
It would be great to see support for text areas.

Also support for [react-maskedinput](https://github.com/insin/react-maskedinput) would make this lib excellent.

I may take a stab at it and submit a PR. Btw, thanks for this straightforward validation solution. I've tried a few others, and this one makes the most sense. It's a shame there are so few stars.

**Comment by Lesha-spr** [comment]
Hi James,

Sorry for late answer.

I believe validation of textarea isn't a common task. If you really need this - please fork.

I've added posibility to wrap Input with some other Component with @1.4.0. Please check <a href="http://lesha-spr.github.io/react-validation/">demo</a> to see usage. I'm not sure if it's a right way to do it. Maybe I'll check this again in the future.

Thanks,
Oleksii
