### ISSUE TITLE
validateAll to return validity?

### ISSUE THREAD

**Issue by snakeyak** [Lesha-spr/react-validation#40]
Sorry to bother with this again, would it be possible for validateAll() method to return true/false to show whether the validations passed or not? Or perhaps an object with non-passed validations as v1.7.5 did?

This is needed when you want to decide on next actions based on the validity. In my case I have a button that upon click checks for all validations within react-validation, as well as some other external things and then submits depending on the outcome

Thanks

**Comment by Lesha-spr** [comment]
Hi @snakeyak ,

Yes, good notice. Could you please apply PR? Or I'll commit it in a few days.

Thanks,
Oleksii

**Comment by snakeyak** [comment]
Hi Oleksii,

I'm really sorry, I tried to do it but got nowhere. If you've got time to commit it I'd greatly appreciate that.

**Comment by Lesha-spr** [comment]
Hi @snakeyak ,

Please check out 52681ed60c18da3ce65839572163189be839a7d8 (v2.0.4). This should resolve an issue.
Also please close an issue if everything is fine.

Thanks,
Oleksii

**Comment by snakeyak** [comment]
works great, thank you
