### ISSUE TITLE
Unknown prop containerClassName

### ISSUE THREAD

**Issue by Cyval** [Lesha-spr/react-validation#41]
I have seen a prop `containerClassName` in the source code in this repo, but whenever I use 

`<Select name="somename" containerClassName="this" />`

It runs, and the div containing the `<select>` tag contains the 'this' className, but in the console, it says:

`Unknown prop 'containerClassName' . . .`

Any workaround? Thanks

**Comment by Lesha-spr** [comment]
Hi @Cyval ,

Which version of React are you using? I've checked for 15.3.0 - no warnings in console.

Thanks,
Oleksii

**Comment by Cyval** [comment]
I'm using React 15.3.0, too. I put the `containerClassName` inside an `Input` component, same warnings.
