### ISSUE TITLE
Indicate requirement of validation props in the documentation

### ISSUE THREAD

**Issue by Cyval** [Lesha-spr/react-validation#42]
This is rather an enhancement. I've noticed that not providing the `validations` prop in an `Input` component causes the console to produce an error.

`this.props._register is not a function`

I suggest that an improvement on the documentation be made, just a minor fix tho. :+1:

**Comment by fraziern** [comment]
Hi I'm working on PR #56 and can add this in. Is the ```validations``` prop required for other components, or just ```Input```?

**Comment by Cyval** [comment]
It is required on all components since each one requires a `validation` prop which I think is being registered in the `Form` component as a whole

**Comment by Lesha-spr** [comment]
Hey guys,

From 2.10.0 validations are just a required property. So I guess it's shouldn't be noticed at README aswell
Please re-open if you have any concerns about it.

Thanks,
Oleksii
