### ISSUE TITLE
showError behavior with other input

### ISSUE THREAD

**Issue by Themandunord** [Lesha-spr/react-validation#44]
Hi @Lesha-spr,

Thanks for your the 2.0 version :)

I use the showError function to show error with an asynchronous function. It's work very well.
But, when I have other input, and I focus to it, the show error of the asynchronous rule disappear.
I think your clear all errors onBlur function.

I've you got an idea to avoid that ? 
Do you need an example ? 

Thanks.
Remy.

**Comment by Lesha-spr** [comment]
Hi @Themandunord ,

Good point. I'll prepare a commit to to avoid this bug.

Thanks,
Oleksii

**Comment by Lesha-spr** [comment]
Hi @Themandunord ,

Please check out 3bb99fc460fb3aaf6af7f7210d3278dfd9ae1c8d. v2.0.6 should help with this bug.

Thanks,
Oleksii

**Comment by Themandunord** [comment]
Thanks @Lesha-spr It works :+1:
