### ISSUE TITLE
Class error on span

### ISSUE THREAD

**Issue by Themandunord** [Lesha-spr/react-validation#46]
Hi @Lesha-spr ,

In your new version (2.0), rules' errors have changed.

Now we have : 
`<div>
  <input />
  <span class="error" />
<div>`

So when I have the error class, I want the span class to be red. Ok it's easy.
But I already want the input field to have a red border... but in CSS I can't select the input field with this error class.

I've missed some property ? 
How to achieve that ? 

Thanks.

**Comment by Lesha-spr** [comment]
Hi @Themandunord ,

Yes, it've changed - for now there is no ```defaults``` for a className highlighting. It is TBD and I'll keep it for some time. You should add ```errorClassName``` prop to your ```Input``` so it'll apply that className on invalidation.

**Comment by Themandunord** [comment]
Yeah, I forgot this property, it does the trick !
Thanks @Lesha-spr
