### ISSUE TITLE
Submit button disabled on Chrome

### ISSUE THREAD

**Issue by Themandunord** [Lesha-spr/react-validation#47]
Hi @Lesha-spr 

When the login form is filled by Chrome, the submit button is still deactivate. But I i make a click anywhere on the page, the submit button is activated.

Thanks.

**Comment by Cyval** [comment]
Hi @Themandunord . 

What do you mean, 'is filled by Chrome'? Does it come from an external API or AJAX call? May I see your code? Thanks

**Comment by Themandunord** [comment]
Hi Cyval, 

You know, when you enter your login/password on a form, chrome asks to save it. 

So when you return on the form later, the form is already filled by chrome. 
So in the login form, my login/password are already filled and and the submit button is disabled. 

When I click everywhere on the page, included the form button, the button is enabled. 

I think the module, react-validation, don't see that the input are validated. 

Thanks

**Comment by asedittlau** [comment]
Hi,

Has anybody found a fix/workaround for this?

Thanks in advance!

**Comment by Themandunord** [comment]
You are facing to this problem too ?

**Comment by crohrer** [comment]
This problem is because of chromes security policy: to prevent autofilled password inputs from being read out by JavaScript without user interaction, the input value is empty (nevertheless is shown filled) until the user clicks somewhere on the page. See:
https://bugs.chromium.org/p/chromium/issues/detail?id=352527

**Comment by asedittlau** [comment]
Yes Themandunord, when page is reload and my login form is autofilled it behaves like you explain.
Thanks crohrer for the info!

**Comment by Lesha-spr** [comment]
Closing this one as non fixable.
