### ISSUE TITLE
How to use with Babel 6 ?

### ISSUE THREAD

**Issue by snakeyak** [Lesha-spr/react-validation#48]
Seems that the usage suggested in documentation doesn't work with new Babel 6 and produces this error:
`Property object of JSXMemberExpression expected node to be of a type ["JSXMemberExpression","JSXIdentifier"] but instead got "MemberExpression"`

I'm guessing it is due to this: https://phabricator.babeljs.io/T6662

<img width="456" alt="screen shot 2016-09-05 at 15 19 37" src="https://cloud.githubusercontent.com/assets/12460995/18250592/31dd57d0-737c-11e6-8cd7-58a4d6762e25.png">

I'm trying to figure out how to use react-validation with the suggested fix, but didn't have much luck.

**Comment by Lesha-spr** [comment]
Hi @snakeyak ,

I'll check it ASAP.

Thanks,
Oleksii

**Comment by snakeyak** [comment]
I've solved this for now by doing this:
```
import Validation from 'react-validation';
...
render() {
      let rules = Validation.rules
      let ValidationForm = Validation.components.Form
      let ValidationInput = Validation.components.Input
      let ValidationButton = Validation.components.Button
...
 <ValidationInput
                      type="text"
                      name="delivery-line"
...
```

Seems to be working that way

**Comment by Lesha-spr** [comment]
From 2.10.* you can import from `react-validation/lib/build/validation.rc` partially.
Ex. `import { Form, Select } from 'react-validation/lib/build/validation.rc'`
