### ISSUE TITLE
Add custom HTML nodes inside containerClass props

### ISSUE THREAD

**Issue by Cyval** [Lesha-spr/react-validation#49]
Hi. This is a suggestion for those who use MaterializeCSS framework and some other CSS frameworks out there. 

I am trying to append an h6 label to my `Input` component., but it messes up because the `h6` turns out to be **outside** the container of the `Input`. An example would be:

```
<div className="row">
              <h6>Date</h6>
              <Input autoComplete="off"
                     type="text"
                     className=""
                     containerClassName="input-field col s6"
                     value=""
                     placeholder="Weight (in cm)"
                     validations={['required']}
              />
</div>
```

Expected Result: 

    Date
    _____________ -> Input component

Actual:

```
Date
    _____________ -> Input component
```

When I traced the code, transferring the `h6` inside the container solves the problem.

UPDATE: Removing the containerClassName and creating a main wrapper for the components solves the problem, however adding this suggestion may increase flexibility for some UI frameworks, especially when icons beside textboxes are an option

**Comment by Lesha-spr** [comment]
Hey @Cyval ,

Not sure how can I help with this. Since React doesn't give a chance to render multiple elements outside of the common scope - I can't provide a **pure** solution here.

I can be not aware of a workaround in this case. If you have (know) any example - please provide and re-open this issue.

Thanks,
Oleksii
