### ISSUE TITLE
Getting react error when moving from input to Validation.Input

### ISSUE THREAD

**Issue by AshMcConnell** [Lesha-spr/react-validation#5]
Hi Folks,

Here is the error I'm getting: - 

Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

Any ideas what I could be doing wrong?

I'm using React 0.14.5

Thanks for your help
All the best,
Ash

**Comment by Lesha-spr** [comment]
Hi Ash,

Could you please provide a broken code example?

Thank you in advance.

**Comment by AshMcConnell** [comment]
Hi Lesha,

Uploaded an attachment (snipped the options in the select for brevity).  I've just started using react, so it could be something silly.

Thanks for your help
Ash

[register-withvalidation.txt](https://github.com/Lesha-spr/react-validation/files/84165/register-withvalidation.txt)

**Comment by AshMcConnell** [comment]
The error goes away when I remove the submit button for some reason - investigating more now

**Comment by Lesha-spr** [comment]
Hm, I can't reproduce this error with provided example code (with or without submit button). Could you please give me more information of usage? What is your build configuration? Is there some errors/warnings during compiling?

Btw, you should add default <option> (label for select) with falsy value (i.e. value='') to make things happaned.

**Comment by AshMcConnell** [comment]
I am using npm for package management and gulp for building.  There are no errors / warnings while compiling.

I am using that component as a "page" 

var Register = require('./pages/register');
...
<Route path="/register" component={Register}/>
...

So it is really the highest level component (after the router itself).  Is there anything I can do to debug?

Thanks!

**Comment by AshMcConnell** [comment]
Success :)

The issue was with multiple react versions that were dependencies of my dependencies (in package.json).  I had to uninstall / reinstall react-images and then uninstall / reinstall react-validation (not sure why for validation).

Sorry for wasting your time, the issue only revealed itself with react-validation for some reason.

Thanks for your help
All the best!
Ash
