### ISSUE TITLE
Value does not propagate if wrapped in react-validation Input

### ISSUE THREAD

**Issue by snakeyak** [Lesha-spr/react-validation#50]
Hi Oleksii,

I discovered a strange bug - it seems that in an Input component, once anything is typed in, react-validate prevents from changing the value indirectly (via state or props, i.e. does not work with an alt / redux store for example)

Here's what happens:
![git](https://cloud.githubusercontent.com/assets/12460995/18369813/e9a7fb18-761f-11e6-9d4e-4562d7a08545.gif)

I produced a minimal example (based on react starter kit), it's all to be seen in components/App/app.js, attached
[validation-bug.zip](https://github.com/Lesha-spr/react-validation/files/462851/validation-bug.zip)

Could you please have a look?

**Comment by mCzolko** [comment]
I'm having exactly the same issue

**Comment by Lesha-spr** [comment]
Hi guys,

Seems all frustrating. Now working to fix this issue.

Thanks,
Oleksii

**Comment by tfinnell** [comment]
@snakeyak this is embarrassingly far from ideal, but the following seems to produce results that are closer to what I'd expect from your example:
```javascript
<ValidationForm ref={ref => this._form = ref}>
    <ValidationInput
      type="text"
      name="delivery-line-1"
      errorClassName='invalid'
      containerClassName="input-wrapper"
      onChange={(e) => { if (!e) return false; this.setState({deliveryLine1: e.target.value}); }}
      value={this.state.deliveryLine1}
      validations={['isRequired']}
    />
  </ValidationForm>

  <input
    className="btn btn-lg btn-primary"
    type='submit'
    value='add text'
    onClick={
      () => {
        const deliveryLine1 = this.state.deliveryLine1 + 'bla';
        this._form.state.states['delivery-line-1'].value = deliveryLine1;
        this.setState({ deliveryLine1 })
      }
    } />
```

@Lesha-spr Any update on a fix for this? I have been digging into the codebase trying to resolve this as well, but would love to get your thoughts on a clean solution. Obviously the above snippet isn't even close in that regard.

**Comment by snakeyak** [comment]
Hi, for now I've forked this and changed this line https://github.com/Lesha-spr/react-validation/blob/master/src/helpers/pull-value.js#L5 to 
```
        value = props.value;
```

This worked, not sure how clean that is, and I do remember there was some undesired behavior as well, although far less undesired than the bug this fixed

**Comment by tfinnell** [comment]
That definitely looks clean enough to me :) The only thing would be handling the issues you mentioned. I'd wager those stem from the need to wait to pull from prop when there's already state present. That needs to toggle with `Form.onSubmit` or `Button.onClick`, but I'm just spit-balling at this point. I'll try to make some time to shift back over to this in a day or two, unless we hear back from Oleksii.

**Comment by Lesha-spr** [comment]
Hey guys,

I've made a lot of updates. Please checkout 2.10.0. This should be fine but please keep me informed about any other issues which may occure.

Thanks,
Oleksii
