### ISSUE TITLE
Uncaught TypeError: error.includes is not a function

### ISSUE THREAD

**Issue by chipit24** [Lesha-spr/react-validation#51]
I have the following form set up:
```js
<Validation.components.Form ref={c => this.form = c} onSubmit={this.handleSubmit.bind(this)}>
  <Validation.components.Input value="" name="my_input" validations={['required']}/>
  <button type="submit">Submit</button>
</Validation.components.Form>
```

My `onSubmit` function:
```js
handleSubmit(event) {
  event.preventDefault();
  this.form.showError('my_input', 'Error');
}
```

My rules:
```js
Object.assign(Validation.rules, {
  required: {
    rule: (value) => {
      return value.trim();
    }
});
```

When I submit the form, I get the following error in the console, regardless of whether or not my input is valid:

```
index.js:2308 Uncaught TypeError: error.includes is not a function
```

When I examine the `error` variable at `index.js:2308`, it gives me the following:
```
Object {0: "E", 1: "r", 2: "r", 3: "o", 4: "r", force: true}
```

How can I get this basic functionality to work?

**Comment by Lesha-spr** [comment]
Hi @chipit24 ,

Have you fixed it? I can't see this error with your example in my setup. Looks like something mutates the form private ```errors``` field.

**Comment by Lesha-spr** [comment]
```String.prototype.includes``` polyfill no needed anymore from 2.10.0.
