### ISSUE TITLE
Uncaught TypeError: value.trim is not a function on demo page

### ISSUE THREAD

**Issue by victor-homyakov** [Lesha-spr/react-validation#52]
[Demo page](http://lesha-spr.github.io/react-validation/) throws `Uncaught TypeError: value.trim is not a function` in `required` validator when trying to validate `Select` component

```js
	        rule: function rule(value) {
	            return value.trim(); // value is an Array
	        },
```

**Comment by Lesha-spr** [comment]
Hi @victor-homyakov ,

Thanks, fixes.
