### ISSUE TITLE
Removed input is not removed from validations

### ISSUE THREAD

**Issue by gleant** [Lesha-spr/react-validation#54]
If I remove input from form, so button stays still disabled state.

**Comment by renakun** [comment]
I'm also experiencing the same issue, any ideas?

**Comment by hectorOviedo** [comment]
Not sure if it's related but when emptying a value of an input, the value comes back from the state on submit.

**Comment by Lesha-spr** [comment]
Hi @gleant , @renakun , @hectorOviedo ,

I've commited 4e90b60104ea67d91f7428bd32ed7a808d295912 (2.0.8) which fixes this issue. Please check it out and close this Issue if everything is ok.

Thanks,
Oleksii

**Comment by gleant** [comment]
I cannot use the newest version because you have removed validateAll from form. So I cannot check out this issue.

**Comment by Lesha-spr** [comment]
Hi @gleant ,

Please checkout 2.10.0. ```validateAll``` returned. But please also check README - it doesn't return errors object. This is TBD but much easier for now.

Thanks,
Oleksii
