### ISSUE TITLE
validateAll()

### ISSUE THREAD

**Issue by ddela-cr** [Lesha-spr/react-validation#57]
is validateAll() no more available? Because it is still in the docs. If it is the case, how should I validate all fields? Thanks

**Comment by Lesha-spr** [comment]
Hi @ddela-cr ,

I'll get it back asap.

**Comment by Lesha-spr** [comment]
Dear @ddela-cr , 

Please checkout 2.10.0. I've returned ```validateAll``` and made a lot of refactoring aswell.
Let me know if something wrong.

Thanks,
Oleksii

**Comment by ddela-cr** [comment]
@Lesha-spr this is working perfectly fine, thanks!
