### ISSUE TITLE
Got an error in IE10

### ISSUE THREAD

**Issue by rexwang** [Lesha-spr/react-validation#59]
Hi there, when I test browser supports, I found out that in IE10, this error will cause script crashes: 

```
 value: function _register(component) {
	            this.components[component.props.name] = component;
 }

Unable to get property 'name' of undefined or null reference
```

I notice in the following code block:

```
var Input = function (_Component) {
	    (0, _inherits3.default)(Input, _Component);

	    function Input(props, context) {
	        (0, _classCallCheck3.default)(this, Input);

	        var _this = (0, _possibleConstructorReturn3.default)(this, (0, _getPrototypeOf2.default)(Input).call(this, props, context));
	        context._register(_this);
	        return _this;
	    }
```
In IE10, '_this' returns

![image](https://cloud.githubusercontent.com/assets/2415029/19449198/68ba151a-9459-11e6-86d6-2f61c19fe065.png)

While in Chrome, Firefox, IE11, '_this' returns

![image](https://cloud.githubusercontent.com/assets/2415029/19449238/93b2951c-9459-11e6-9d02-e977c895e9f9.png)

@Lesha-spr I really like this plugin you made, but IE10 support is required for me. Please take a look at it. Thanks.

**Comment by Lesha-spr** [comment]
Dear @rexwang ,

Could you please check 2.10.0 about this issue? Demo is now up to date.
Please let me know about the results.

Thanks,
Oleksii

**Comment by Lesha-spr** [comment]
Fixed with https://github.com/Lesha-spr/react-validation/commit/60ca24f7a0e0b65df49ad4dafa7ac1b7ec6cd4bb.

**Comment by rexwang** [comment]
@Lesha-spr When I install the latest version, I got this error:

![image](https://cloud.githubusercontent.com/assets/2415029/19572681/263f67ba-96b8-11e6-8364-e820e6f7d8a8.png)

This is the file I added to my site, is it correct? `node_modules/react-validation/gh-compile/main.js`

**Comment by Lesha-spr** [comment]
Hi @rexwang ,

Don't you use any bundler to build your app? Webpack/gulp? This is how you're controlling dependencies.
Shortly no, you should add `lib/build/validation.js`. But I'm not surely about the behavior without any bundler tool.

**Comment by rexwang** [comment]
Hi @Lesha-spr I am using require.js, in yourr 2.0.8build, I just need to include the index.js file in  the build directory. So now I need to run bundler first?

**Comment by Lesha-spr** [comment]
No you don't. Try to import `react-validation/lib/build/validation.js`.
