### ISSUE TITLE
Possible to compare fields?

### ISSUE THREAD

**Issue by AshMcConnell** [Lesha-spr/react-validation#6]
Is it possible to validate fields with eachother, specifically I want to validate that password and passwordConfirmation fields match.

Thanks!
Ash

**Comment by Lesha-spr** [comment]
Hi Ash,

Yes, it's surely a common task for validation. I'll make commit on holidays.

Thanks,
Oleksii

**Comment by AshMcConnell** [comment]
Thanks Oleksii, I thought I was missing an option, that would be a nice addition to the library, thanks!

**Comment by Lesha-spr** [comment]
For now you can use Dummy-implementation.
Please check <a href="http://lesha-spr.github.io/react-validation/">demo</a> for code usage.

**Comment by AshMcConnell** [comment]
Thanks, I'll give that a try!

**Comment by AshMcConnell** [comment]
Just a note for when you are implementing, the demo doesn't block / disable the submit button if the passwords don't match.  I'll try to disable manually.

**Comment by Lesha-spr** [comment]
Hi Ash,

Sorry for late answer. Please checkout 1.4.2 version and <a href="http://lesha-spr.github.io/react-validation/">demo</a> for example usage.

If everything is OK - please close this issue.

Thanks,
Oleksii

**Comment by Lesha-spr** [comment]
I believe this should be closed via 1.4.2

**Comment by JanMesaric** [comment]
This does not work with version 1.7.5. Fields are no validated for equality.
