### ISSUE TITLE
Meteor - File not found (Components)

### ISSUE THREAD

**Issue by Cyval** [Lesha-spr/react-validation#60]
Hi, I'm using Meteor and have encountered these errors while building the app.

    While building the application:
    error: File not found: node_modules/react-validation/src/components/Button.react.jsx
    error: File not found: node_modules/react-validation/src/components/Form.react.jsx
    error: File not found: node_modules/react-validation/src/components/Input.react.jsx
    error: File not found: node_modules/react-validation/src/components/Select.react.jsx
    error: File not found: node_modules/react-validation/src/components/Textarea.react.jsx
    error: File not found: node_modules/react-validation/src/validation.jsx

Is there any workaround here? Or update in the Readme? thanks

**Comment by Lesha-spr** [comment]
Hi @Cyval ,

Have you updated to the latest version? Try to completely uninstall/install the library.

**Comment by Cyval** [comment]
Hi, uninstalling and reinstalling does the job. 
Does it also solve an issue with `lib/build/validations.js 1:103`?

Because it works in my local, but when we deploy it into our staging site, we get this error in our galaxy server:
`cannot find module 'classnames' lib/build/validations.js `:103`

Just updated to 2.10.3 now, 2.0.4 is the one used in our staging site.

**Comment by Lesha-spr** [comment]
`classnames` listed as peer dependency. You should install it too to get things work.

**Comment by Cyval** [comment]
It already is, and is added in my node_modules. Anyway, I'll re-deploy the app. I'll just close this one when the problem disappears. Thanks

**Comment by Cyval** [comment]
Here's an update: 
<img width="969" alt="download" src="https://cloud.githubusercontent.com/assets/15729358/19542853/d99a14c2-96a4-11e6-8d10-52df39cee2f2.png">

And here's my classnames inside my app 
node_modules:
![selection_043](https://cloud.githubusercontent.com/assets/15729358/19542941/91a90f1e-96a5-11e6-9ad8-ca8bb629235d.png)

**Comment by Lesha-spr** [comment]
Could you please try to import from `react-validation/lib/src/validation` and paste trace than?

Thanks

**Comment by Cyval** [comment]
It's okay now, just listed the classnames in my package.json. Thanks
