### ISSUE TITLE
no passing event values?

### ISSUE THREAD

**Issue by snakeyak** [Lesha-spr/react-validation#61]
Hi Oleksii,

The 2.10.4 version does not seem to be passing event values anymore (previous versions did)

And as such e.g. this code does no longer work:
```
<ValidationInput
                        type="text"
                        name="lname"
                        errorClassName="invalid"
                        containerClassName="input-wrapper"
                        value={this.props.lastName}
                        onChange={(e) => { if (!e) return false; BookingActions.updateLastName(e.target.value); }}
                        validations={['isRequired', 'isName']}
                      />
```

<img width="1428" alt="screen shot 2016-10-22 at 12 36 45" src="https://cloud.githubusercontent.com/assets/12460995/19619045/706a1554-9854-11e6-9b0a-56f2c9b8ddf9.png">

**Comment by Lesha-spr** [comment]
Hi @snakeyak ,

Fixed with 2.10.5. Please check out.

Thanks,
Oleksii
