### ISSUE TITLE
How to cancle the initial validate when Form componnet mount

### ISSUE THREAD

**Issue by heimuya** [Lesha-spr/react-validation#63]
I'd like to generate a form and add some validation rules. But if I did not set the default value in Input component and the validations inlcude "required", the error hint could show when the Form componet initial mounted. I find that the Form component in react-validation including the following code:
"
componentDidMount() {
    this.validateState();
}
"
Maybe this caused the situation explained. Could you give me some suggestion?

**Comment by heimuya** [comment]
I find that the state (isUsed, isChanged) of component affect the hint of rules showing or not. But if I use some other notification packages or librarys, it is diffcult to control the notification, and the notification shows whenever the Form component mounted.

**Comment by Lesha-spr** [comment]
Hey @heimuya ,

We must validate initial state to disable or not the `Button` components. Could you please provide some sample of the issue you're facing?

Thanks,
Oleksii

**Comment by heimuya** [comment]
@Lesha-spr Thank you for your response. My issue is the notification info always shown first when Form component mounted. I use Notice as the third library to show the notification info, so the rules of required is:
required: {
        rule: (value, components) => {
            return value.toString().trim();
        },
        hint: (value) => {
            Notice.error({
                message: "Required!",
                duration: 2000
            })

            return null;
        }
},
Due to the fact that validateState function is running when Form component mounted, and the value of Input component is null or empty string, the rule would return false, so the hint will run. The result is Notice always running when the page loaded at first.
What's more, the onBlur event of one component will caused the validation of all the component in the Form component. Maybe I am not understand the package clearly, hope you can give some suggestions, thank you again.

**Comment by Lesha-spr** [comment]
Hey @heimuya ,

I'm now working on other issue and the fix should also resolve your issue. As I can see you need to call `Notice.error` **ONLY** when actual error occurs but the current solution calls the `hint` on mount.

After fix `hint` would be called on `render` with `isChanged && isUsed` condition so I believe you will be fine.

Thanks,
Oleksii

**Comment by heimuya** [comment]
@Lesha-spr Thank you, and expect your new version.

**Comment by Lesha-spr** [comment]
Hey @heimuya ,

Please checkout v2.10.7. Should be fine. Please also close the issue after acceptance.

Thanks,
Oleksii

**Comment by heimuya** [comment]
@Lesha-spr Thank you. However, I find the issue still exist. Maybe this issue is caused by the third library Notice can not read the state of the component. I tried to change the rule as following and it works:
```javascript
required: {
        // Function to validate value
        rule: (value, components) => {
            let flag = true;
            Object.keys(components).forEach((index) => {
              let component = components[index];
              if(component.state.isUsed && component.state.isChanged) {
                flag = false;
              }
            });

            return flag || value.toString().trim();
        },
        // Function to return hint
        // You may use current value to inject it in some way to the hint
        hint: (value) => {
            Notice.error({
                message: "请填写必要信息",
                duration: 2000
            })

            return false;
        }
    },
```
But another issue is the onBlur event of a component will emit the validateState to check all the other compoents, and this maybe also caused by the state (isUsed and isChanged) can not read by the third party. 
My question is not normal and others would never face. So, thank you again, and I will close the question.
