### ISSUE TITLE
Build non-uglified version as well?

### ISSUE THREAD

**Issue by phillipj** [Lesha-spr/react-validation#64]
Hey there,

first of all, thanks for a good validator package 👍 

I'm currently having some issue while writing tests on my components which again uses validator components. What I'm seeing is that validator components doesn't shallowly render components I expect.

#### Test
```js
const tree = shallow(
  <Validation.components.Form>
    <Validation.components.Input value='email@email.com' name='email' validations={['required', 'email']}/>
    <Validation.components.Button>Submit</Validation.components.Button>
  </Validation.components.Form>
);

console.log(tree.debug());
```

#### Output
```html
<form>
  <t value="email@email.com" name="email" validations={{...}} />
  <p>
    Submit
  </p>
</form>
```

After quite some time digging, I noticed the main file exposed by this package, uses uglify in the build process. I tried building this package locally without uglify, and I start seeing the rendered markup I'd expect:

```html
<form>
  <Input value="email@email.com" name="email" validations={{...}} />
  <Button>
    Submit
  </Button>
</form>
```

I see why uglifying is beneficial for UMD users / projects without build steps, tho not really needed when we've got a build step. Could we support both worlds? Using webpack to transpile down to ES5 and UMD is just fine for both, but getting hold of a version which is simply not uglified would be great.

Two options comes to mind:

1. Don't uglify `lib/build/validation.js` and save the uglified version as `lib/build/validation.min.js`
2. Uglify `lib/build/validation.js`  and save the non-uglified version as `lib/build/validation.build.js`

IMO option 1 is the most natural option, but option 2 would avoid a breaking change for the current users of this package.

Any thoughts?

**Comment by Lesha-spr** [comment]
Hey @phillipj ,

Good catch. You're totally right. I'll push the update asap.

Thanks,
Oleksii

**Comment by Lesha-spr** [comment]
Done with 2.10.7

Please checkout and close the issue if everything is fine.

Thanks,
Oleksii

**Comment by phillipj** [comment]
@Lesha-spr sorry for the late response to your lightning quick fix!

Just tested with react-validation@2.10.9 and can confirm it works just as expected now, thanks 💯
