### ISSUE TITLE
error when triggering showError

### ISSUE THREAD

**Issue by cfpinto** [Lesha-spr/react-validation#66]
I'm getting and error when triggering an error. does anybody have an idea of it might be?

warning.js:36 Warning: Failed context type: Invalid context `errors.voucher[0]` of type `object` supplied to `Input`, expected `string`.
    in Input (created by InputWithLabel)
    in div (created by InputWithLabel)
    in div (created by InputWithLabel)
    in InputWithLabel (created by Payment)
    in div (created by Payment)
    in div (created by Payment)
    in ReactCSSTransitionGroupChild (created by ReactTransitionGroup)
    in div (created by ReactTransitionGroup)
    in ReactTransitionGroup (created by ReactCSSTransitionGroup)
    in ReactCSSTransitionGroup (created by Collapsible)
    in div (created by Collapsible)
    in Collapsible (created by Payment)
    in div (created by Payment)
    in form (created by Form)
    in Form (created by Payment)
    in ReactCSSTransitionGroupChild (created by ReactTransitionGroup)
    in div (created by ReactTransitionGroup)
    in ReactTransitionGroup (created by ReactCSSTransitionGroup)
    in ReactCSSTransitionGroup (created by Payment)
    in div (created by Payment)
    in div (created by Payment)
    in div (created by Payment)
    in Payment (created by withRouter(Payment))
    in withRouter(Payment) (created by PaymentContainer)
    in PaymentContainer (created by Connect(PaymentContainer))
    in Connect(PaymentContainer) (created by RouterContext)
    in ReactCSSTransitionGroupChild (created by ReactTransitionGroup)
    in div (created by ReactTransitionGroup)
    in ReactTransitionGroup (created by ReactCSSTransitionGroup)
    in ReactCSSTransitionGroup (created by Main)
    in div (created by Main)
    in Main (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in ProviderprintWarning @ warning.js:36warning @ warning.js:60checkReactTypeSpec @ checkReactTypeSpec.js:81_checkContextTypes @ ReactCompositeComponent.js:535_processContext @ ReactCompositeComponent.js:484updateComponent @ ReactCompositeComponent.js:590receiveComponent @ ReactCompositeComponent.js:544receiveComponent @ ReactReconciler.js:126obj.(anonymous function) @ backend.js:8386updateChildren @ ReactChildReconciler.js:110_reconcilerUpdateChildren @ ReactMultiChild.js:210_updateChildren @ ReactMultiChild.js:314updateChildren @ ReactMultiChild.js:301_updateDOMChildren @ ReactDOMComponent.js:942updateComponent @ ReactDOMComponent.js:760receiveComponent @ ReactDOMComponent.js:718receiveComponent @ ReactReconciler.js:126obj.(anonymous function) @ backend.js:8386updateChildren @ ReactChildReconciler.js:110_reconcilerUpdateChildren @ ReactMultiChild.js:210_updateChildren @ ReactMultiChild.js:314updateChildren @ ReactMultiChild.js:301_updateDOMChildren @ ReactDOMComponent.js:942updateComponent @ ReactDOMComponent.js:760receiveComponent @ ReactDOMComponent.js:718receiveComponent @ ReactReconciler.js:126obj.(anonymous function) @ backend.js:8386_updateRenderedComponent @ ReactCompositeComponent.js:751_performComponentUpdate @ ReactCompositeComponent.js:721updateComponent @ ReactCompositeComponent.js:642receiveComponent @ ReactCompositeComponent.js:544receiveComponent @ ReactReconciler.js:126obj.(anonymous function) @ backend.js:8386updateChildren @ ReactChildReconciler.js:110_reconcilerUpdateChildren @ ReactMultiChild.js:210_updateChildren @ ReactMultiChild.js:314updateChildren @ ReactMultiChild.js:301_updateDOMChildren @ ReactDOMComponent.js:942updateComponent @ ReactDOMComponent.js:760receiveComponent @ ReactDOMComponent.js:718receiveComponent @ ReactReconciler.js:126obj.(anonymous function) @ backend.js:8386updateChildren @ ReactChildReconciler.js:110_reconcilerUpdateChildren @ ReactMultiChild.js:210_updateChildren @ ReactMultiChild.js:314updateChildren @ ReactMultiChild.js:301_updateDOMChildren @ ReactDOMComponent.js:942updateComponent @ ReactDOMComponent.js:760receiveComponent @ ReactDOMComponent.js:718receiveComponent @ ReactReconciler.js:126obj.(anonymous function) @ backend.js:8386_updateRenderedComponent @ ReactCompositeComponent.js:751_performComponentUpdate @ ReactCompositeComponent.js:721updateComponent @ ReactCompositeComponent.js:642receiveComponent @ ReactCompositeComponent.js:544receiveComponent @ ReactReconciler.js:126obj.(anonymous function) @ backend.js:8386updateChildren @ ReactChildReconciler.js:110_reconcilerUpdateChildren @ ReactMultiChild.js:210_updateChildren @ ReactMultiChild.js:314updateChildren @ ReactMultiChild.js:301_updateDOMChildren @ ReactDOMComponent.js:942updateComponent @ ReactDOMComponent.js:760receiveComponent @ ReactDOMComponent.js:718receiveComponent @ ReactReconciler.js:126obj.(anonymous function) @ backend.js:8386_updateRenderedComponent @ ReactCompositeComponent.js:751_performComponentUpdate @ ReactCompositeComponent.js:721updateComponent @ ReactCompositeComponent.js:642receiveComponent @ ReactCompositeComponent.js:544receiveComponent @ ReactReconciler.js:126obj.(anonymous function) @ backend.js:8386_updateRenderedComponent @ ReactCompositeComponent.js:751_performComponentUpdate @ ReactCompositeComponent.js:721updateComponent @ ReactCompositeComponent.js:642receiveComponent @ ReactCompositeComponent.js:544receiveComponent @ ReactReconciler.js:126obj.(anonymous function) @ backend.js:8386updateChildren @ ReactChildReconciler.js:110_reconcilerUpdateChildren @ ReactMultiChild.js:210_updateChildren @ ReactMultiChild.js:314updateChildren @ ReactMultiChild.js:301_updateDOMChildren @ ReactDOMComponent.js:942updateComponent @ ReactDOMComponent.js:760receiveComponent @ ReactDOMComponent.js:718receiveComponent @ ReactReconciler.js:126obj.(anonymous function) @ backend.js:8386_updateRenderedComponent @ ReactCompositeComponent.js:751_performComponentUpdate @ ReactCompositeComponent.js:721updateComponent @ ReactCompositeComponent.js:642receiveComponent @ ReactCompositeComponent.js:544receiveComponent @ ReactReconciler.js:126obj.(anonymous function) @ backend.js:8386updateChildren @ ReactChildReconciler.js:110_reconcilerUpdateChildren @ ReactMultiChild.js:210_updateChildren @ ReactMultiChild.js:314updateChildren @ ReactMultiChild.js:301_updateDOMChildren @ ReactDOMComponent.js:942updateComponent @ ReactDOMComponent.js:760receiveComponent @ ReactDOMComponent.js:718receiveComponent @ ReactReconciler.js:126obj.(anonymous function) @ backend.js:8386updateChildren @ ReactChildReconciler.js:110_reconcilerUpdateChildren @ ReactMultiChild.js:210_updateChildren @ ReactMultiChild.js:314updateChildren @ ReactMultiChild.js:301_updateDOMChildren @ ReactDOMComponent.js:942updateComponent @ ReactDOMComponent.js:760receiveComponent @ ReactDOMComponent.js:718receiveComponent @ ReactReconciler.js:126obj.(anonymous function) @ backend.js:8386_updateRenderedComponent @ ReactCompositeComponent.js:751_performComponentUpdate @ ReactCompositeComponent.js:721updateComponent @ ReactCompositeComponent.js:642performUpdateIfNecessary @ ReactCompositeComponent.js:558performUpdateIfNecessary @ ReactReconciler.js:158obj.(anonymous function) @ backend.js:8386runBatchedUpdates @ ReactUpdates.js:151perform @ Transaction.js:138perform @ Transaction.js:138perform @ ReactUpdates.js:90flushBatchedUpdates @ ReactUpdates.js:173closeAll @ Transaction.js:204perform @ Transaction.js:151batchedUpdates @ ReactDefaultBatchingStrategy.js:63enqueueUpdate @ ReactUpdates.js:201enqueueUpdate @ ReactUpdateQueue.js:25enqueueCallback @ ReactUpdateQueue.js:124ReactComponent.setState @ ReactComponent.js:66Form._this.showError @ validation.js:765(anonymous function) @ configureValidation.js:151
warning.js:36 Warning: Failed context type: Invalid context `errors.voucher[0]` of type `object` supplied to `Button`, expected `string`.
    in Button (created by Payment)
    in div (created by Payment)
    in div (created by Payment)
    in form (created by Form)
    in Form (created by Payment)
    in ReactCSSTransitionGroupChild (created by ReactTransitionGroup)
    in div (created by ReactTransitionGroup)
    in ReactTransitionGroup (created by ReactCSSTransitionGroup)
    in ReactCSSTransitionGroup (created by Payment)
    in div (created by Payment)
    in div (created by Payment)
    in div (created by Payment)
    in Payment (created by withRouter(Payment))
    in withRouter(Payment) (created by PaymentContainer)
    in PaymentContainer (created by Connect(PaymentContainer))
    in Connect(PaymentContainer) (created by RouterContext)
    in ReactCSSTransitionGroupChild (created by ReactTransitionGroup)
    in div (created by ReactTransitionGroup)
    in ReactTransitionGroup (created by ReactCSSTransitionGroup)
    in ReactCSSTransitionGroup (created by Main)
    in div (created by Main)
    in Main (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in Provider

**Comment by Lesha-spr** [comment]
Hey @cfpinto ,

Could you please provide the source-code on which you're facing the error?

**Comment by cfpinto** [comment]
Hi @Lesha-spr,

see the source code attached

```jsx

function _handleVoucherChange() {
    const form = this.refs.form;
    api.post(URL_VOUCHER_CHECK, {voucher: value})
        .then(response => {
            form.showError(name, <div className="info">{response.message[0]}</div>)
        })
        .catch(err => {
            form.showError(name, <div className="error">{response.error[0]}</div>)
        });
}
```

thx

**Comment by Lesha-spr** [comment]
Hey @cfpinto ,

`showError` API has been changed. It's now accepts the error string as a second argument mapped to the errors `extend`

```javascript
Object.assign(Validation.errors, {
    apiError: {
        hint: value => <div className="error">Error message</div>
    }
});

// ...
api.post()
    .catch(err => {
        form.showError(name, 'apiError')
    });
```

I can now see that it's not enough to display `response` properties (which is pretty common). I'll mark this as a enhancement and apply the changed ASAP.

Thanks,
Oleksii

**Comment by Lesha-spr** [comment]
Hey @cfpinto ,

Please checkout v2.10.9 and the update to your code is:

```javascript
function _handleVoucherChange(evt) {
            const form = this.refs.form;
            api.post(URL_VOUCHER_CHECK, {voucher: value})
                .then(response => {
                    form.showError(name, (value) => {
                        return <div className="info">{response.message[0]}</div>
                    })
                })
                .catch(err => {
                    form.showError(name,  (value) => {
                        return <div className="info">{response.message[0]}</div>
                    })
                });
        }
```
