### ISSUE TITLE
error occur if implement the onBlur event on Input component

### ISSUE THREAD

**Issue by restaur** [Lesha-spr/react-validation#67]
When i testing the input component and handle the blur event, the onBlur is occur error because event target is null, so i try to review the source code on Base.jsx, it seem has call the event.persist() but why it's called in the setState() inner function? I think it should write before the setState function, also maybe has something consider?

now
```
onBlur = (event) => {
        this.setState({
            isUsed: true
        }, () => {
            this.context.validateState(this.props.name);

            event.persist();

            (this.props.onBlur || noop)(event);
        });
    };
```

should
```
onBlur = (event) => {
        event.persist();
        
        this.setState({
            isUsed: true
        }, () => {
            this.context.validateState(this.props.name);

            (this.props.onBlur || noop)(event);
        });
    };
```

**Comment by Lesha-spr** [comment]
Hi @restaur ,

Yes, you're right. Thanks for notice.

**Comment by Lesha-spr** [comment]
Fixed. Please check out v2.10.9.

Thanks,
Oleksii
