### ISSUE TITLE
Does not validates input in child component with ES6

### ISSUE THREAD

**Issue by abhayn-webonise** [Lesha-spr/react-validation#7]
I am new to react js and I am not able to add validation for child components. I have a main component and within that component I have <Validation.Form>.

`
<Validation.Form className='createGroupForm clearfix' id='createGroupForm'>
  <Validation.Input ref='username' name='username' validations={[{rule: 'isEmail'}]} />
  <ListItemWrapper items={this.state.items}  />
</Validation.Form>
`

In ListItemWrapper I have an input where I have to add validation but _validate and _registeredControl are noting getting bound to the input.

**Comment by Lesha-spr** [comment]
Hi Abhay,

I'll try to make it possible without any major changes. But in general I would not like to pass Form ref, accept this ref as argument and attach Input to it. I believe it's not the way it should be.

Thanks,
Oleksii

**Comment by Lesha-spr** [comment]
Could not reproduce.
