### ISSUE TITLE
not clear how to use validator functions with options

### ISSUE THREAD

**Issue by justin-hackin** [Lesha-spr/react-validation#9]
i.e. is it  
```
{rule:'isLength', min:8}
OR
{rule:'isLength', options:{min:8}}
```

**Comment by Lesha-spr** [comment]
Hi Justin,

What is the purpose of this options? When you're extend the Validation via `extendErrors` you can provide any of options in the `rule` function.

I can imagine some 'connection' to it through the `validation`'s object properties. But I'm not sure it is necessary.

Could you please provide exemplary use-case of this interface as you want it to be?

Thank you in advance.

**Comment by Lesha-spr** [comment]
Hi @justin-hackin ,

Could you please answer or maybe I can close it?

Thanks,
Oleksii

**Comment by kaela** [comment]
@justin-hackin The original documentation for passing in the options is incorrect.

Inline, set a new rule to a rule name (note that you cannot use `isLength` as the rule name here:
```
validations={[{
    rule: 'descriptionLength'
}]}
```

Then, in your extender, define the options like this:

````
descriptionLength: {
    className: 'ui-input_state_empty',
    message: 'Length must be less than 60',
    rule: function(value) {
        return Boolean(Validation.validator.isLength(value, 0, 60));
    }
  }
````

**Comment by Lesha-spr** [comment]
Not an issue/bug
